version: 2
jobs:
  test_jdk8_with_coverage:
    working_directory: ~/flo
    docker:
      # TODO: Remove pinning after debian has fixed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925
      - image: maven:3.5.4-jdk-8@sha256:1be6e59e3cec4587637101f4e834c41e5576d8bc48e065f095f88289451bac51
        command: ["/bin/bash"]
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
      - run:
          environment:
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B dependency:go-offline compile test-compile
      - save_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          environment:
            # Java heap size
            JAVA: java -Xmx256m -Xms256m
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B verify scala:doc-jar -Pcoverage
      - run: bash <(curl -s https://codecov.io/bash)

  test_jdk10:
    working_directory: ~/styx
    docker:
      - image: maven:3.5.4-jdk-10-slim
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-jdk10-{{ checksum "pom.xml" }}
      - run:
          environment:
            # Maven heap size
            MAVEN_OPTS: -Xmx1024m -Xms1024m
          command: mvn -B dependency:go-offline compile test-compile
      - save_cache:
          key: v1-deps-jdk10-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn -B verify scala:doc-jar

workflows:
  version: 2
  build:
    jobs:
      - test_jdk8_with_coverage:
          filters:
            branches:
              ignore: gh-pages
# FIXME
#      - test_jdk10:
#          filters:
#            branches:
#              ignore: gh-pages
